# -*- coding: utf-8 -*-
"""[004]_digit_using _Randomforest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rRYyRVCWXn6RBFq6IhlWhlskCO7Isc9
"""

import pandas as pd
import numpy as np

from sklearn.datasets import load_digits
digits = load_digits()

import matplotlib.pyplot as plt
plt.gray()
for i in range(4):
  plt.matshow(digits.images[i])
  plt.show()

digits.data[:5]

df=pd.DataFrame(digits.data)
df.head()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df,digits.target,test_size=0.2)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)

model.score(x_test,y_test)

y_pred=model.predict(x_test)
y_pred

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sn
sn.heatmap(cm,annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')

import pickle

with open("model.pkl", "wb") as file:
    pickle.dump(model, file)

# Load model
with open("model.pkl", "rb") as file:
    loaded_model = pickle.load(file)

prediction = loaded_model.predict(x_test)
print(prediction)